plugins {
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'iceandfire-nicktale'
}

repositories {
    mavenCentral()
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation files("../nicktale-api-neoforge/build/libs/nicktaleapi-${nicktale_api_version}.jar")
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xmaxerrs' << '3000'
    options.encoding = 'UTF-8'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}
