package com.nicktale.mccompat.@MODID@.@SET@;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.IntFunction;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.codec.StreamDecoder;
import net.minecraft.network.codec.StreamEncoder;

/**
 * Generated by gradle/mc-preprocess.gradle for Minecraft 26.3, which removed FriendlyByteBuf's list helpers.
 * Same wire format as 26.2 (VarInt size, then the elements).
 */
public final class McBuf {
    private McBuf() {
    }

    public static <B extends FriendlyByteBuf, T> List<T> readList(B buf, StreamDecoder<? super B, T> decoder) {
        return readCollection(buf, ArrayList::new, decoder);
    }

    public static <B extends FriendlyByteBuf, T, C extends Collection<T>> C readCollection(B buf, IntFunction<C> factory,
            StreamDecoder<? super B, T> decoder) {
        int size = buf.readVarInt();
        C out = factory.apply(size);
        for (int i = 0; i < size; i++) {
            out.add(decoder.decode(buf));
        }
        return out;
    }

    public static <B extends FriendlyByteBuf, T> void writeCollection(B buf, Collection<T> values, StreamEncoder<? super B, T> encoder) {
        buf.writeVarInt(values.size());
        for (T value : values) {
            encoder.encode(buf, value);
        }
    }
}
